services:
  web:
    container_name: k9-frontend
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '5000:3000'
    volumes:
      - './web:/app/web'
    env_file:
      - ./web/.env
    command: ["npm", "run", "dev", "--", "-H", "0.0.0.0"]
#  api:
#    container_name: k9-backend
#    image: node:23.0.0
#    working_dir: /app/api
#    env_file:
#      - .env
#    volumes:
#      - './api:/app/api'
#    ports:
#      - '3000:3000'
#    command: ['npm', 'run', 'start:dev']

#   db:
#     container_name: k9-db
#     image: postgres:16
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=default
#     ports:
#       - '4000:5432'
#     volumes:
#       - ./db:/var/lib/postgresql/data

# volumes:
#   db:
#     driver: local